packages:
  - 'packages/jaeger-ui'
  - 'packages/plexus'

allowBuilds:
  cpu-features: false
  protobufjs: false
  ssh2: false

catalog:
  '@noble/hashes': 2.4.0
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.73ce44ef507f7c2aed23bc5addd747d0e3d0b33a
  vitest: 5.0.1
  vite-plus: 0.0.0-commit.73ce44ef507f7c2aed23bc5addd747d0e3d0b33a
  '@vitest/coverage-v8': 5.0.1

minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-core@0.0.0-commit.73ce44ef507f7c2aed23bc5addd747d0e3d0b33a'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.0.0-commit.73ce44ef507f7c2aed23bc5addd747d0e3d0b33a'
  - '@voidzero-dev/vite-plus-darwin-x64@0.0.0-commit.73ce44ef507f7c2aed23bc5addd747d0e3d0b33a'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.0.0-commit.73ce44ef507f7c2aed23bc5addd747d0e3d0b33a'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.0.0-commit.73ce44ef507f7c2aed23bc5addd747d0e3d0b33a'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.0.0-commit.73ce44ef507f7c2aed23bc5addd747d0e3d0b33a'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.0.0-commit.73ce44ef507f7c2aed23bc5addd747d0e3d0b33a'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.0.0-commit.73ce44ef507f7c2aed23bc5addd747d0e3d0b33a'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.0.0-commit.73ce44ef507f7c2aed23bc5addd747d0e3d0b33a'
  - vite-plus@0.0.0-commit.73ce44ef507f7c2aed23bc5addd747d0e3d0b33a
overrides:
  react: 19.3.0
  react-dom: 19.3.0
  yaml: 2.9.0
  '@types/node': 24.13.1
  '@exodus/bytes>@noble/hashes': 'catalog:'
  '@assistant-ui/core': 0.3.3
  '@assistant-ui/store': 0.3.2
  '@assistant-ui/tap': 0.9.9
  brace-expansion: 5.0.9
  browserslist: 4.28.8
  fast-uri: 4.1.3
  vite@*: 'catalog:'
  vitest@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
